version: "3.8"

services:
    php:
        container_name: laravel_php
        build:
            context: docker/php
        tty: true
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${APP_PORT}:8080"
        volumes:
            - ./:/var/www/html:cached
        depends_on: [mariaDB]

    mariaDB:
        container_name: laravel_maria
        image: mariadb:11.3.2
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - db_volume:/var/lib/mysql

volumes:
    db_volume:

networks:
    default:
        name: learn-laravel
